<a href="https://colab.research.google.com/github/yeahtigerr/hylee-ml-2021-spring/blob/main/usage_of_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

生成tensor：

In [ ]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.from_numpy(np.array([[1, 2], [3, 4]]))
z1 = torch.zeros([2, 2])
z2 = torch.zeros_like(x)  # 生成元素全部为0的张量，形状与输入参数（另一个张量）相同
x, y, z1, z2

(tensor([[1, 2],
         [3, 4]]), tensor([[1, 2],
         [3, 4]]), tensor([[0., 0.],
         [0., 0.]]), tensor([[0, 0],
         [0, 0]]))

torch.squeeze  将输入张量维度值为1的维度压缩
torch.unsqueeze 在输入张量参数维度处增添一个维度为1的维度

In [ ]:
x = torch.zeros([1, 2, 2, 3])
y = x.squeeze(0)
z = x.unsqueeze(1)
x.shape, y.shape, z.shape

(torch.Size([1, 2, 2, 3]), torch.Size([2, 2, 3]), torch.Size([1, 1, 2, 2, 3]))

torch.cat用于将多个tensor进行拼接操作(应用时必须保证除拼接dim外，其他dim尺寸相同)

In [ ]:
x = torch.zeros([2, 1, 3])
y = torch.zeros([2, 2, 3])
z = torch.zeros([2, 3, 3])
w = torch.cat([x, y, z], dim=1)
w.shape

torch.Size([2, 6, 3])

用torch进行张量的基础运算

In [3]:
x = torch.tensor([2,3,4])
y = torch.tensor([1,1,1])
x-y, x.pow(2),x.sum(), x.float().mean()  # 在计算mean()时，需将数据类型转换为float，否则会报错

(tensor([1, 2, 3]), tensor([ 4,  9, 16]), tensor(9), tensor(3.))

In [4]:
x.to('cuda')

tensor([2, 3, 4], device='cuda:0')

In [5]:
torch.cuda.is_available()

True

利用torch求导

In [6]:
x = torch.tensor([[1., 0.],[-1., 1.]], requires_grad=True)
z = x.pow(2).sum()
z.backward()
x.grad

tensor([[ 2.,  0.],
        [-2.,  2.]])